--
${footerText!"This message was autogenerated by AgNO3 FileShield."}
[#if !footerText?has_content && adminContact?has_content]
If this message is unsolicited or you believe you recieved it in 
error you may contact the administrators at <${adminContact}>.
[/#if]